window.config = {name: '凌极云',logo: '/logo.png',rootUrl: '/',frameworkRoot: '/Framework',slogan: '凌极云，让教学更高效',components: {'topbar': {'messageUrl': '','loginUrl': '/Views/User/Portal/logon.html','logonUrl': '/Views/User/Portal/logon.html','logoutUrl': '/Views/User/Portal/logout.html','identityUrl': '/Views/User/Portal/select-unit.html','personUrl': '/Views/User/Account/index.html','groupUrl': '','behaviorUrl': '','projectUrl': '','imageUrl': '/Static/','messageUrl': '','gatewayUrl': '/Views/Personal/Desktop/index.html'},'soundCheck': {'audio': '/Static/SC/Guide.mp3','wave': '/Static/SC/Guide.wf3'},'extensions': {'wechat': true}}};













































